/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoteRouteImport } from './routes/vote'
import { Route as TierListRouteImport } from './routes/tier-list'
import { Route as SkinsRouteImport } from './routes/skins'
import { Route as PatchNotesRouteImport } from './routes/patch-notes'
import { Route as OstRouteImport } from './routes/ost'
import { Route as ItemsRouteImport } from './routes/items'
import { Route as IncidentRouteImport } from './routes/incident'
import { Route as DraftRouteImport } from './routes/draft'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CountersRouteImport } from './routes/counters'
import { Route as ContributorsRouteImport } from './routes/contributors'
import { Route as ContributeRouteImport } from './routes/contribute'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ArcanaRouteImport } from './routes/arcana'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HeroesIndexRouteImport } from './routes/heroes/index'
import { Route as HeroesHeroIdRouteImport } from './routes/heroes/$heroId'

const VoteRoute = VoteRouteImport.update({
  id: '/vote',
  path: '/vote',
  getParentRoute: () => rootRouteImport,
} as any)
const TierListRoute = TierListRouteImport.update({
  id: '/tier-list',
  path: '/tier-list',
  getParentRoute: () => rootRouteImport,
} as any)
const SkinsRoute = SkinsRouteImport.update({
  id: '/skins',
  path: '/skins',
  getParentRoute: () => rootRouteImport,
} as any)
const PatchNotesRoute = PatchNotesRouteImport.update({
  id: '/patch-notes',
  path: '/patch-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const OstRoute = OstRouteImport.update({
  id: '/ost',
  path: '/ost',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsRoute = ItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentRoute = IncidentRouteImport.update({
  id: '/incident',
  path: '/incident',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftRoute = DraftRouteImport.update({
  id: '/draft',
  path: '/draft',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CountersRoute = CountersRouteImport.update({
  id: '/counters',
  path: '/counters',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributorsRoute = ContributorsRouteImport.update({
  id: '/contributors',
  path: '/contributors',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributeRoute = ContributeRouteImport.update({
  id: '/contribute',
  path: '/contribute',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ArcanaRoute = ArcanaRouteImport.update({
  id: '/arcana',
  path: '/arcana',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HeroesIndexRoute = HeroesIndexRouteImport.update({
  id: '/heroes/',
  path: '/heroes/',
  getParentRoute: () => rootRouteImport,
} as any)
const HeroesHeroIdRoute = HeroesHeroIdRouteImport.update({
  id: '/heroes/$heroId',
  path: '/heroes/$heroId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/arcana': typeof ArcanaRoute
  '/auth': typeof AuthRoute
  '/contribute': typeof ContributeRoute
  '/contributors': typeof ContributorsRoute
  '/counters': typeof CountersRoute
  '/dashboard': typeof DashboardRoute
  '/draft': typeof DraftRoute
  '/incident': typeof IncidentRoute
  '/items': typeof ItemsRoute
  '/ost': typeof OstRoute
  '/patch-notes': typeof PatchNotesRoute
  '/skins': typeof SkinsRoute
  '/tier-list': typeof TierListRoute
  '/vote': typeof VoteRoute
  '/heroes/$heroId': typeof HeroesHeroIdRoute
  '/heroes/': typeof HeroesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/arcana': typeof ArcanaRoute
  '/auth': typeof AuthRoute
  '/contribute': typeof ContributeRoute
  '/contributors': typeof ContributorsRoute
  '/counters': typeof CountersRoute
  '/dashboard': typeof DashboardRoute
  '/draft': typeof DraftRoute
  '/incident': typeof IncidentRoute
  '/items': typeof ItemsRoute
  '/ost': typeof OstRoute
  '/patch-notes': typeof PatchNotesRoute
  '/skins': typeof SkinsRoute
  '/tier-list': typeof TierListRoute
  '/vote': typeof VoteRoute
  '/heroes/$heroId': typeof HeroesHeroIdRoute
  '/heroes': typeof HeroesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/arcana': typeof ArcanaRoute
  '/auth': typeof AuthRoute
  '/contribute': typeof ContributeRoute
  '/contributors': typeof ContributorsRoute
  '/counters': typeof CountersRoute
  '/dashboard': typeof DashboardRoute
  '/draft': typeof DraftRoute
  '/incident': typeof IncidentRoute
  '/items': typeof ItemsRoute
  '/ost': typeof OstRoute
  '/patch-notes': typeof PatchNotesRoute
  '/skins': typeof SkinsRoute
  '/tier-list': typeof TierListRoute
  '/vote': typeof VoteRoute
  '/heroes/$heroId': typeof HeroesHeroIdRoute
  '/heroes/': typeof HeroesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/analytics'
    | '/arcana'
    | '/auth'
    | '/contribute'
    | '/contributors'
    | '/counters'
    | '/dashboard'
    | '/draft'
    | '/incident'
    | '/items'
    | '/ost'
    | '/patch-notes'
    | '/skins'
    | '/tier-list'
    | '/vote'
    | '/heroes/$heroId'
    | '/heroes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/analytics'
    | '/arcana'
    | '/auth'
    | '/contribute'
    | '/contributors'
    | '/counters'
    | '/dashboard'
    | '/draft'
    | '/incident'
    | '/items'
    | '/ost'
    | '/patch-notes'
    | '/skins'
    | '/tier-list'
    | '/vote'
    | '/heroes/$heroId'
    | '/heroes'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/analytics'
    | '/arcana'
    | '/auth'
    | '/contribute'
    | '/contributors'
    | '/counters'
    | '/dashboard'
    | '/draft'
    | '/incident'
    | '/items'
    | '/ost'
    | '/patch-notes'
    | '/skins'
    | '/tier-list'
    | '/vote'
    | '/heroes/$heroId'
    | '/heroes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ArcanaRoute: typeof ArcanaRoute
  AuthRoute: typeof AuthRoute
  ContributeRoute: typeof ContributeRoute
  ContributorsRoute: typeof ContributorsRoute
  CountersRoute: typeof CountersRoute
  DashboardRoute: typeof DashboardRoute
  DraftRoute: typeof DraftRoute
  IncidentRoute: typeof IncidentRoute
  ItemsRoute: typeof ItemsRoute
  OstRoute: typeof OstRoute
  PatchNotesRoute: typeof PatchNotesRoute
  SkinsRoute: typeof SkinsRoute
  TierListRoute: typeof TierListRoute
  VoteRoute: typeof VoteRoute
  HeroesHeroIdRoute: typeof HeroesHeroIdRoute
  HeroesIndexRoute: typeof HeroesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vote': {
      id: '/vote'
      path: '/vote'
      fullPath: '/vote'
      preLoaderRoute: typeof VoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tier-list': {
      id: '/tier-list'
      path: '/tier-list'
      fullPath: '/tier-list'
      preLoaderRoute: typeof TierListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skins': {
      id: '/skins'
      path: '/skins'
      fullPath: '/skins'
      preLoaderRoute: typeof SkinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patch-notes': {
      id: '/patch-notes'
      path: '/patch-notes'
      fullPath: '/patch-notes'
      preLoaderRoute: typeof PatchNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ost': {
      id: '/ost'
      path: '/ost'
      fullPath: '/ost'
      preLoaderRoute: typeof OstRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items': {
      id: '/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incident': {
      id: '/incident'
      path: '/incident'
      fullPath: '/incident'
      preLoaderRoute: typeof IncidentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/draft': {
      id: '/draft'
      path: '/draft'
      fullPath: '/draft'
      preLoaderRoute: typeof DraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counters': {
      id: '/counters'
      path: '/counters'
      fullPath: '/counters'
      preLoaderRoute: typeof CountersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contributors': {
      id: '/contributors'
      path: '/contributors'
      fullPath: '/contributors'
      preLoaderRoute: typeof ContributorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contribute': {
      id: '/contribute'
      path: '/contribute'
      fullPath: '/contribute'
      preLoaderRoute: typeof ContributeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arcana': {
      id: '/arcana'
      path: '/arcana'
      fullPath: '/arcana'
      preLoaderRoute: typeof ArcanaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heroes/': {
      id: '/heroes/'
      path: '/heroes'
      fullPath: '/heroes/'
      preLoaderRoute: typeof HeroesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heroes/$heroId': {
      id: '/heroes/$heroId'
      path: '/heroes/$heroId'
      fullPath: '/heroes/$heroId'
      preLoaderRoute: typeof HeroesHeroIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AnalyticsRoute: AnalyticsRoute,
  ArcanaRoute: ArcanaRoute,
  AuthRoute: AuthRoute,
  ContributeRoute: ContributeRoute,
  ContributorsRoute: ContributorsRoute,
  CountersRoute: CountersRoute,
  DashboardRoute: DashboardRoute,
  DraftRoute: DraftRoute,
  IncidentRoute: IncidentRoute,
  ItemsRoute: ItemsRoute,
  OstRoute: OstRoute,
  PatchNotesRoute: PatchNotesRoute,
  SkinsRoute: SkinsRoute,
  TierListRoute: TierListRoute,
  VoteRoute: VoteRoute,
  HeroesHeroIdRoute: HeroesHeroIdRoute,
  HeroesIndexRoute: HeroesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
