/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TierListRouteImport } from './routes/tier-list'
import { Route as SkinsRouteImport } from './routes/skins'
import { Route as CountersRouteImport } from './routes/counters'
import { Route as ContributorsRouteImport } from './routes/contributors'
import { Route as ContributeRouteImport } from './routes/contribute'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HeroesIndexRouteImport } from './routes/heroes/index'
import { Route as HeroesHeroIdRouteImport } from './routes/heroes/$heroId'

const TierListRoute = TierListRouteImport.update({
  id: '/tier-list',
  path: '/tier-list',
  getParentRoute: () => rootRouteImport,
} as any)
const SkinsRoute = SkinsRouteImport.update({
  id: '/skins',
  path: '/skins',
  getParentRoute: () => rootRouteImport,
} as any)
const CountersRoute = CountersRouteImport.update({
  id: '/counters',
  path: '/counters',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributorsRoute = ContributorsRouteImport.update({
  id: '/contributors',
  path: '/contributors',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributeRoute = ContributeRouteImport.update({
  id: '/contribute',
  path: '/contribute',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HeroesIndexRoute = HeroesIndexRouteImport.update({
  id: '/heroes/',
  path: '/heroes/',
  getParentRoute: () => rootRouteImport,
} as any)
const HeroesHeroIdRoute = HeroesHeroIdRouteImport.update({
  id: '/heroes/$heroId',
  path: '/heroes/$heroId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/contribute': typeof ContributeRoute
  '/contributors': typeof ContributorsRoute
  '/counters': typeof CountersRoute
  '/skins': typeof SkinsRoute
  '/tier-list': typeof TierListRoute
  '/heroes/$heroId': typeof HeroesHeroIdRoute
  '/heroes/': typeof HeroesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/contribute': typeof ContributeRoute
  '/contributors': typeof ContributorsRoute
  '/counters': typeof CountersRoute
  '/skins': typeof SkinsRoute
  '/tier-list': typeof TierListRoute
  '/heroes/$heroId': typeof HeroesHeroIdRoute
  '/heroes': typeof HeroesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/contribute': typeof ContributeRoute
  '/contributors': typeof ContributorsRoute
  '/counters': typeof CountersRoute
  '/skins': typeof SkinsRoute
  '/tier-list': typeof TierListRoute
  '/heroes/$heroId': typeof HeroesHeroIdRoute
  '/heroes/': typeof HeroesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/analytics'
    | '/contribute'
    | '/contributors'
    | '/counters'
    | '/skins'
    | '/tier-list'
    | '/heroes/$heroId'
    | '/heroes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/analytics'
    | '/contribute'
    | '/contributors'
    | '/counters'
    | '/skins'
    | '/tier-list'
    | '/heroes/$heroId'
    | '/heroes'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/analytics'
    | '/contribute'
    | '/contributors'
    | '/counters'
    | '/skins'
    | '/tier-list'
    | '/heroes/$heroId'
    | '/heroes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ContributeRoute: typeof ContributeRoute
  ContributorsRoute: typeof ContributorsRoute
  CountersRoute: typeof CountersRoute
  SkinsRoute: typeof SkinsRoute
  TierListRoute: typeof TierListRoute
  HeroesHeroIdRoute: typeof HeroesHeroIdRoute
  HeroesIndexRoute: typeof HeroesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tier-list': {
      id: '/tier-list'
      path: '/tier-list'
      fullPath: '/tier-list'
      preLoaderRoute: typeof TierListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skins': {
      id: '/skins'
      path: '/skins'
      fullPath: '/skins'
      preLoaderRoute: typeof SkinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counters': {
      id: '/counters'
      path: '/counters'
      fullPath: '/counters'
      preLoaderRoute: typeof CountersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contributors': {
      id: '/contributors'
      path: '/contributors'
      fullPath: '/contributors'
      preLoaderRoute: typeof ContributorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contribute': {
      id: '/contribute'
      path: '/contribute'
      fullPath: '/contribute'
      preLoaderRoute: typeof ContributeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heroes/': {
      id: '/heroes/'
      path: '/heroes'
      fullPath: '/heroes/'
      preLoaderRoute: typeof HeroesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heroes/$heroId': {
      id: '/heroes/$heroId'
      path: '/heroes/$heroId'
      fullPath: '/heroes/$heroId'
      preLoaderRoute: typeof HeroesHeroIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AnalyticsRoute: AnalyticsRoute,
  ContributeRoute: ContributeRoute,
  ContributorsRoute: ContributorsRoute,
  CountersRoute: CountersRoute,
  SkinsRoute: SkinsRoute,
  TierListRoute: TierListRoute,
  HeroesHeroIdRoute: HeroesHeroIdRoute,
  HeroesIndexRoute: HeroesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
